### ISSUE TITLE
Use firebase image and title as mete data for page dynamically based on query string in URL

### ISSUE THREAD

**Issue by MerlinOfCode** [dalenguyen/firebase-wordpress-docs#4]
Brother, I have used your shortcode to display firebase dynamically to create a share link from the app.  Can you help me write a script which will use the image, title, and portion of story as the meta seo data for nice link previews?  If I use my regular wordpress seo feature, the meta image and other data will be the same for all stories.  I would like the title, description, and image to change based on the document in the query string.  

Please give me an estimate and I will pay.

Thank you!

**Comment by dalenguyen** [comment]
This is not related to the document. Please post to the plugin repo. https://github.com/dalenguyen/firebase-wordpress-plugin
